server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: Api-Gateway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: false
  main:
    web-application-type: reactive