spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: r2dbc:postgresql://localhost:5432/Api-Gateway?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
